Week-1 - Implementation of ErrorOr
GeorgiyKozak/scala-course-2022-spring pull request #1
Opened 2022-05-24 21:44 UTC by GeorgiyKozak

2022-05-24 22:05 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week1/homework/adt.scala
> +        case ErrorOr.Some(v)   => try f(v) catch {
Nobody did it with `try-catch` at the first attempt. I hope you got the idea why `f(v)` should be wrapped into `try-catch`.

2022-05-24 22:05 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week1/homework/adt.scala
> +      if v == null then ErrorOr.Error(NullPointerException()) else ErrorOr.Some(v)
Always provide a useful message when throwing/passing an exception.

2022-05-24 22:06 UTC, IgorWolkov requested changes
Minor comment.

2022-05-24 22:14 UTC, GeorgiyKozak commented on src/main/scala/karazin/scala/users/group/week1/homework/adt.scala
> +        case ErrorOr.Some(v)   => try f(v) catch {
In the last lecture you said that we should consider that the method f(v) can throw an exception. f(v) is some function in the body of which an exception can be thrown, right?

2022-05-24 22:27 UTC, GeorgiyKozak commented on src/main/scala/karazin/scala/users/group/week1/homework/adt.scala
> +        case ErrorOr.Some(v)   => try f(v) catch {
In the last lecture you said that we should consider that the function f(v) can throw an exception. f(v) is some function in the body of which an exception can be thrown, right?

2022-05-24 22:45 UTC, GeorgiyKozak commented on src/main/scala/karazin/scala/users/group/week1/homework/adt.scala
> +        case ErrorOr.Some(v)   => try f(v) catch {
In the last lecture you said that we should consider that the function f(v) can throw an exception. f(v) is some function in the body of which an exception can be thrown or f(v) can return ErrorOr.Error?

2022-05-25 19:06 UTC, GeorgiyKozak commented on src/main/scala/karazin/scala/users/group/week1/homework/adt.scala
> +        case ErrorOr.Some(v)   => try f(v) catch {
In the last lecture you said that we should consider that the function f(v) can throw an exception. f(v) is some function in the body of which an exception can be thrown or f(v) can return ErrorOr.Error?

2022-05-25 22:43 UTC, IgorWolkov approved these changes
Well done!

2022-06-01 11:31 UTC, merged